steps:
- name: 'maven'
  args: ['mvn', 'clean','install']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/transaction-data-exporter', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-microservice-java'

- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'transactionDataExporter', 
   'transactionDataExporter=gcr.io/$PROJECT_ID/transaction-data-exporter:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-microservice-java'

images: [
   'gcr.io/$PROJECT_ID/transaction-data-exporter:latest'
  ]