steps:
- name: 'maven'
  args: ['mvn', 'clean','install','deploy']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/transaction-data-exporter', '.']
images: ['gcr.io/$PROJECT_ID/transaction-data-exporter']
