kind: Service
apiVersion: v1
metadata:
  name: transaction-data-exporter
spec:
  selector:
     run: transaction-data-exporter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  type: LoadBalancer
