kind: Service
apiVersion: v1
metadata:
  name: transactionDataExporter
spec:
  selector:
     run: transactionDataExporter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  type: LoadBalancer